services:
  postgres:
    image: postgres:latest
    container_name: produto_api_postgres 
    environment:
      POSTGRES_USER: devuser 
      POSTGRES_PASSWORD: devpassword 
      POSTGRES_DB: produto_db 
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - produto_api_network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  api:
    build:
        context: ../src
        dockerfile: ./Api/Api/Dockerfile
    container_name: produto_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ProdutoConnection: "Host=produto_api_postgres;Database=produto_db;Username=devuser;Password=devpassword"
      ConnectionStrings__RedisConnection: "redis:6379"
    ports:
      - "5000:80"
    networks:
      - produto_api_network
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis-data:

networks:
  produto_api_network:
    driver: bridge
