name: Pipeline
on:
  push:
    branches: ["main"]
jobs:
  build:
    name: Pipeline de CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      - name: Checkout do código
        uses: actions/checkout@v2
      - name: Execução do Teste de Unidade
        run: dotnet test ProdutoApi/src/Tests/Tests/Tests.csproj
      - name: Publicando a API
        run: dotnet publish ProdutoApi/src/Api/Api/Api.csproj